#!/data/data/com.termux/files/usr/bin/bash

echo "Starting mass installation with pacman. Overwriting all files if needed..."

# Define the packages (from your provided list)
packages=(
    abseil-cpp
    apt
    attr
    attr-glibc
    bash
    bash-completion
    binutils
    binutils-glibc
    brotli
    bzip2
    bzip2-glibc
    ca-certificates
    ca-certificates-glibc
    clang
    coreutils
    coreutils-glibc
    curl
    curl-glibc
    dash
    debianutils
    dialog
    diffutils
    dos2unix
    dpkg
    ed
    findutils
    findutils-glibc
    gawk
    gcc-libs
    gdbm
    gdbm-glibc
    git
    glib
    glib-glibc
    glibc
    gnupg
    gpgme
    grep
    grep-glibc
    gzip
    inetutils
    jq
    krb5
    krb5-glibc
    ldns
    less
    less-glibc
    libacl
    libacl-glibc
    libandroid-glob
    libandroid-posix-semaphore
    libandroid-selinux
    libandroid-support
    libandroid-utimes
    libarchive
    libassuan
    libbz2
    libbz2-glibc
    libc++
    libcap
    libcap-glibc
    libcap-ng
    libcap-ng-glibc
    libcrypt
    libcurl
    libcurl-glibc
    libdb
    libdb-glibc
    libdebuginfod
    libedit
    libelf
    libelf-glibc
    libevent
    libevent-glibc
    libexpat
    libffi
    libffi-glibc
    libgcrypt
    libgirepository
    libgmp
    libgnutls
    libgpg-error
    libiconv
    libidn2
    libidn2-glibc
    libjansson
    libksba
    libllvm
    liblz4
    liblz4-glibc
    liblzma
    liblzma-glibc
    libmd
    libmpfr
    libnettle
    libnghttp2
    libnghttp2-glibc
    libnghttp3
    libnpth
    libpam
    libpam-glibc
    libpcre
    libpcre2
    libpcre2-glibc
    libperl
    libpsl
    libresolv-wrapper
    libsqlite
    libssh2
    libssh2-glibc
    libtalloc
    libtirpc
    libunbound
    libunistring
    libunistring-glibc
    libunwind
    libunwind-glibc
    libuuid
    libuuid-glibc
    libverto
    libverto-glibc
    libxcrypt
    libxml2
    linux-api-headers
    lsof
    make
    nano
    ncurses
    ncurses-glibc
    ncurses-ui-libs
    ndk-sysroot
    net-tools
    oniguruma
    openssh
    openssh-sftp-server
    openssl
    openssl-glibc
    pacman
    patch
    patchelf
    pcre
    pcre2
    perl
    pinentry
    pkg-config
    procps
    psmisc
    readline
    resolv-conf
    sed
    sed-glibc
    strace
    tar
    tar-glibc
    util-linux
    util-linux-glibc
    wget
    which
    zlib
    zlib-glibc
    zsh
    zstd
    zstd-glibc
)

# Run pacman with overwrite to bypass conflicts
for package in "${packages[@]}"; do
    echo "Installing $package with overwrite..."
    pacman -S --noconfirm --overwrite="*" "$package"
done

echo "All packages installed with --overwrite='*'. Please check for stability issues!"